# Generated by Django 5.0.4 on 2024-06-18 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombresCliente', models.CharField(max_length=50)),
                ('apellidoPaternoCliente', models.CharField(max_length=50)),
                ('apellidoMaternoCliente', models.CharField(blank=True, max_length=50, null=True)),
                ('emailCliente', models.CharField(max_length=9)),
                ('contraseniaCliente', models.CharField(max_length=128)),
                ('estatusCliente', models.CharField(max_length=1)),
                ('esVerificadoCliente', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'cliente',
                'ordering': ['apellidoPaternoCliente'],
            },
        ),
        migrations.CreateModel(
            name='CorteCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempoCorte', models.DateTimeField(auto_now_add=True, unique=True)),
            ],
            options={
                'db_table': 'corteCaja',
            },
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoPostal', models.CharField(max_length=5)),
                ('asentamiento', models.CharField(max_length=50)),
                ('mnpio', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
                ('idAsentaCodigoPostal', models.CharField(max_length=5)),
            ],
            options={
                'verbose_name': 'Direccion',
                'verbose_name_plural': 'Direcciones',
                'db_table': 'direccion',
                'ordering': ['codigoPostal', 'asentamiento'],
            },
        ),
        migrations.CreateModel(
            name='Domicilio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calleDomicilio', models.CharField(max_length=50)),
                ('numeroExteriorDomicilio', models.CharField(default='s/n', max_length=10)),
                ('codigoPostalDomicilio', models.CharField(max_length=5)),
                ('coloniaDomicilio', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Domicilio',
                'verbose_name_plural': 'Domicilios',
                'db_table': 'domicilio',
                'ordering': ['codigoPostalDomicilio'],
            },
        ),
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('editorial', models.CharField(default='Sin Editorial', max_length=50)),
            ],
            options={
                'verbose_name': 'Editorial',
                'verbose_name_plural': 'Editoriales',
                'db_table': 'editorial',
                'ordering': ['editorial'],
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombresEmpleado', models.CharField(max_length=50)),
                ('apellidoPaternoEmpleado', models.CharField(max_length=50)),
                ('apellidoMaternoEmpleado', models.CharField(blank=True, max_length=50, null=True)),
                ('usuarioEmpleado', models.CharField(max_length=9)),
                ('contraseniaEmpleado', models.CharField(max_length=128)),
                ('tipoEmpleado', models.CharField(max_length=3)),
                ('turnoEmpleado', models.CharField(max_length=1)),
                ('estatusEmpleado', models.CharField(max_length=1)),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'db_table': 'empleado',
                'ordering': ['apellidoPaternoEmpleado'],
            },
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tituloLibro', models.CharField(max_length=100)),
                ('isbnLibro', models.CharField(max_length=13)),
                ('resumenLibro', models.CharField(blank=True, max_length=500, null=True)),
                ('precioLibro', models.DecimalField(decimal_places=2, max_digits=7)),
                ('stockLibro', models.IntegerField(default=0)),
                ('descuento', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=3, null=True)),
                ('portadalibro', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
            options={
                'verbose_name': 'Libro',
                'verbose_name_plural': 'Libros',
                'db_table': 'libro',
                'ordering': ['tituloLibro'],
            },
        ),
        migrations.CreateModel(
            name='TipoEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcionTipoEmpleado', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'tipoEmpleado',
            },
        ),
        migrations.CreateModel(
            name='TipoTransaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoTransaccion', models.CharField(max_length=3, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo de Transaccion',
                'verbose_name_plural': 'Tipo de Transacciones',
                'db_table': 'tipoTransaccion',
                'ordering': ['tipoTransaccion'],
            },
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempoTransaccion', models.DateTimeField(auto_now_add=True, unique=True)),
                ('precioTransaccion', models.DecimalField(decimal_places=2, max_digits=7)),
                ('totalTransaccion', models.DecimalField(decimal_places=2, max_digits=10)),
                ('piezasTransaccion', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Transaccion',
                'verbose_name_plural': 'Transacciones',
                'db_table': 'transaccion',
                'ordering': ['tiempoTransaccion'],
            },
        ),
        migrations.CreateModel(
            name='DireccionInterDomicilio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idDireccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libroStoreNet.direccion')),
                ('idDomicilio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libroStoreNet.domicilio')),
            ],
            options={
                'db_table': 'Direccion_domicilio',
            },
        ),
        migrations.CreateModel(
            name='ClienteInterDomicilio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libroStoreNet.cliente')),
                ('idDomicilio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libroStoreNet.domicilio')),
            ],
            options={
                'db_table': 'cliente_domicilio',
            },
        ),
        migrations.CreateModel(
            name='CorteCajaInterEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idCorteCaja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libroStoreNet.cortecaja')),
                ('idEmpleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libroStoreNet.empleado')),
            ],
            options={
                'db_table': 'corteCaja_empleado',
            },
        ),
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(default='Sin Autor', max_length=50)),
                ('libros', models.ManyToManyField(related_name='autores', to='libroStoreNet.libro')),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
                'db_table': 'autor',
                'ordering': ['autor'],
            },
        ),
        migrations.CreateModel(
            name='LibroInterEditorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idEditorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libroStoreNet.editorial')),
                ('idLibro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libroStoreNet.libro')),
            ],
            options={
                'db_table': 'libro_editorial',
            },
        ),
        migrations.CreateModel(
            name='EmpleadoInterTipoEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idEmpleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libroStoreNet.empleado')),
                ('idTipoEmpleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libroStoreNet.tipoempleado')),
            ],
            options={
                'db_table': 'empleado_tipoEmpleado',
            },
        ),
        migrations.CreateModel(
            name='EmpleadoInterTransaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idEmpleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libroStoreNet.empleado')),
                ('idTransaccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libroStoreNet.transaccion')),
            ],
            options={
                'db_table': 'empleado_transaccion',
            },
        ),
        migrations.CreateModel(
            name='ClienteInterTransaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libroStoreNet.cliente')),
                ('idTransaccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libroStoreNet.transaccion')),
            ],
            options={
                'db_table': 'cliente_transaccion',
            },
        ),
        migrations.CreateModel(
            name='TransaccionInterTipoTransaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idTipoTransaccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libroStoreNet.tipotransaccion')),
                ('idTransaccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libroStoreNet.transaccion')),
            ],
            options={
                'db_table': 'transaccion_tipoTransaccion',
            },
        ),
        migrations.AddConstraint(
            model_name='direccioninterdomicilio',
            constraint=models.UniqueConstraint(fields=('idDomicilio', 'idDireccion'), name='unique_Direccion_domicilio'),
        ),
        migrations.AddConstraint(
            model_name='clienteinterdomicilio',
            constraint=models.UniqueConstraint(fields=('idDomicilio', 'idCliente'), name='unique_cliente_domicilio'),
        ),
        migrations.AddConstraint(
            model_name='cortecajainterempleado',
            constraint=models.UniqueConstraint(fields=('idEmpleado', 'idCorteCaja'), name='unique_corteCaja_empleado'),
        ),
        migrations.AddConstraint(
            model_name='librointereditorial',
            constraint=models.UniqueConstraint(fields=('idLibro', 'idEditorial'), name='unique_libro_editorial'),
        ),
        migrations.AddConstraint(
            model_name='empleadointertipoempleado',
            constraint=models.UniqueConstraint(fields=('idEmpleado', 'idTipoEmpleado'), name='unique_empleado_tipoEmpleado'),
        ),
        migrations.AddConstraint(
            model_name='empleadointertransaccion',
            constraint=models.UniqueConstraint(fields=('idEmpleado', 'idTransaccion'), name='unique_empleado_transaccion'),
        ),
        migrations.AddConstraint(
            model_name='clienteintertransaccion',
            constraint=models.UniqueConstraint(fields=('idTransaccion', 'idCliente'), name='unique_cliente_transaccion'),
        ),
        migrations.AddConstraint(
            model_name='transaccionintertipotransaccion',
            constraint=models.UniqueConstraint(fields=('idTransaccion', 'idTipoTransaccion'), name='unique_transaccion_tipoTransaccion'),
        ),
    ]
