# Generated by Django 5.0.6 on 2024-06-20 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'db_table': 'categoria',
                'ordering': ['categoria'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombresCliente', models.CharField(max_length=50)),
                ('apellidoPaternoCliente', models.CharField(max_length=50)),
                ('apellidoMaternoCliente', models.CharField(blank=True, max_length=50, null=True)),
                ('emailCliente', models.CharField(max_length=30)),
                ('contraseniaCliente', models.CharField(max_length=128)),
                ('estatusCliente', models.CharField(max_length=1)),
                ('esVerificadoCliente', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'cliente',
                'ordering': ['apellidoPaternoCliente'],
            },
        ),
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('editorial', models.CharField(default='Sin Editorial', max_length=50)),
            ],
            options={
                'verbose_name': 'Editorial',
                'verbose_name_plural': 'Editoriales',
                'db_table': 'editorial',
                'ordering': ['editorial'],
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombresEmpleado', models.CharField(max_length=50)),
                ('apellidoPaternoEmpleado', models.CharField(max_length=50)),
                ('apellidoMaternoEmpleado', models.CharField(blank=True, max_length=50, null=True)),
                ('usuarioEmpleado', models.CharField(max_length=9)),
                ('contraseniaEmpleado', models.CharField(max_length=128)),
                ('turnoEmpleado', models.CharField(max_length=1)),
                ('estatusEmpleado', models.CharField(max_length=1)),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'db_table': 'empleado',
                'ordering': ['apellidoPaternoEmpleado'],
            },
        ),
        migrations.CreateModel(
            name='TipoTransaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoTransaccion', models.CharField(max_length=3, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo de Transaccion',
                'verbose_name_plural': 'Tipo de Transacciones',
                'db_table': 'tipoTransaccion',
                'ordering': ['tipoTransaccion'],
            },
        ),
        migrations.CreateModel(
            name='Domicilio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calleDomicilio', models.CharField(max_length=50)),
                ('numeroExteriorDomicilio', models.CharField(default='s/n', max_length=10)),
                ('codigoPostalDomicilio', models.CharField(max_length=5)),
                ('coloniaDomicilio', models.CharField(max_length=50)),
                ('municipioDomicilio', models.CharField(default=0, max_length=50)),
                ('estadoDomicilio', models.CharField(default=0, max_length=50)),
                ('cliente', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='domicilio', to='libroStoreNet.cliente')),
            ],
            options={
                'verbose_name': 'Domicilio',
                'verbose_name_plural': 'Domicilios',
                'db_table': 'domicilio',
                'ordering': ['codigoPostalDomicilio'],
            },
        ),
        migrations.CreateModel(
            name='CorteCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempoCorte', models.DateTimeField(auto_now_add=True, unique=True)),
                ('empleados', models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='libroStoreNet.empleado')),
            ],
            options={
                'verbose_name': 'Corte de Caja',
                'verbose_name_plural': 'Cortes de Caja',
                'db_table': 'corteCaja',
                'ordering': ['tiempoCorte'],
            },
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tituloLibro', models.CharField(max_length=100)),
                ('isbnLibro', models.CharField(max_length=13)),
                ('resumenLibro', models.CharField(blank=True, max_length=500, null=True)),
                ('precioLibro', models.DecimalField(decimal_places=2, max_digits=7)),
                ('stockLibro', models.IntegerField(default=0)),
                ('descuento', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=3, null=True)),
                ('portadalibro', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='libroStoreNet.categoria')),
                ('editorial', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='librosPublicados', to='libroStoreNet.editorial')),
            ],
            options={
                'verbose_name': 'Libro',
                'verbose_name_plural': 'Libros',
                'db_table': 'libro',
                'ordering': ['tituloLibro'],
            },
        ),
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(default='Sin Autor', max_length=50)),
                ('libros', models.ManyToManyField(related_name='autores', to='libroStoreNet.libro')),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
                'db_table': 'autor',
                'ordering': ['autor'],
            },
        ),
        migrations.CreateModel(
            name='TipoEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcionTipoEmpleado', models.CharField(max_length=20, unique=True)),
                ('empleados', models.ManyToManyField(related_name='tipoEmpleados', to='libroStoreNet.empleado')),
            ],
            options={
                'db_table': 'tipoEmpleado',
                'ordering': ['descripcionTipoEmpleado'],
            },
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempoTransaccion', models.DateTimeField(auto_now_add=True, unique=True)),
                ('totalTransaccion', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='libroStoreNet.cliente')),
                ('empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='libroStoreNet.empleado')),
                ('tipoTransaccion', models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='libroStoreNet.tipotransaccion')),
            ],
            options={
                'verbose_name': 'Transaccion',
                'verbose_name_plural': 'Transacciones',
                'db_table': 'transaccion',
                'ordering': ['tiempoTransaccion'],
            },
        ),
        migrations.CreateModel(
            name='TransaccionInterLibro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=7)),
                ('piezas', models.PositiveIntegerField()),
                ('idLibro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libroStoreNet.libro')),
                ('idTransaccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libroStoreNet.transaccion')),
            ],
            options={
                'db_table': 'transaccion_libro',
            },
        ),
        migrations.AddField(
            model_name='transaccion',
            name='libros',
            field=models.ManyToManyField(through='libroStoreNet.TransaccionInterLibro', to='libroStoreNet.libro'),
        ),
        migrations.AddConstraint(
            model_name='transaccioninterlibro',
            constraint=models.UniqueConstraint(fields=('idTransaccion', 'idLibro'), name='unique_transaccion_libro'),
        ),
    ]
